DELETE http://localhost:3003/api/blogs/67ae037d2c791b09beaf32fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcndhbCIsImlkIjoiNjdhZGZmYmI2YjgxN2NkMDZjOTE1YjE2IiwiaWF0IjoxNzM5NDU2NDU0LCJleHAiOjE3Mzk0NjAwNTR9.6nksl1N_XKfbwfXjXloJcFbMvwjYminyKkskI9kphZI